apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksk8sdecbootcamp-cef1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksk8sdecbootcamp-cef1"
  template:
    metadata:
      labels:
        app: "aksk8sdecbootcamp-cef1"
    spec:
      containers:
        - name: "aksk8sdecbootcamp-cef1"
          image: "crk8sdecbootcamppa4ccr22z5d7y.azurecr.io/aksk8sdecbootcamp"
          ports:
          - containerPort: 80