apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksk8sdecbootcamp-cef1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksk8sdecbootcamp-cef1"
  template:
    metadata:
      labels:
        app: "aksk8sdecbootcamp-cef1"
    spec:
      containers:
        - name: "aksk8sdecbootcamp-cef1"
          image: "crk8sdecbootcamppa4ccr22z5d7y.azurecr.io/aksk8sdecbootcamp"
          ports:
          - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      containers:
      - name: azure-vote-back
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis