on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: crk8sdecbootcamppa4ccr22z5d7y.azurecr.io
        username: ${{ secrets.acr_crk8sdecbootcamppa4ccr22z5d7y_username }}
        password: ${{ secrets.acr_crk8sdecbootcamppa4ccr22z5d7y_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t crk8sdecbootcamppa4ccr22z5d7y.azurecr.io/aksk8sdecbootcamp:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push crk8sdecbootcamppa4ccr22z5d7y.azurecr.io/aksk8sdecbootcamp:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksk8sdecbootcamp_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-k8s-dec-bootcamp9dfd | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-k8s-dec-bootcamp9dfd`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-k8s-dec-bootcamp9dfd
        container-registry-url: crk8sdecbootcamppa4ccr22z5d7y.azurecr.io
        container-registry-username: ${{ secrets.acr_crk8sdecbootcamppa4ccr22z5d7y_username }}
        container-registry-password: ${{ secrets.acr_crk8sdecbootcamppa4ccr22z5d7y_password }}
        secret-name: aksk8sdecboodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-k8s-dec-bootcamp9dfd
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          crk8sdecbootcamppa4ccr22z5d7y.azurecr.io/aksk8sdecbootcamp:${{ github.sha }}
        imagepullsecrets: |
          aksk8sdecboodockerauth
